"""ORM models for inter-store inventory transfers.

See docs/M8_ADVANCED_INVENTORY_DESIGN.md "Design Decisions 6-8" for the
full design. Summary of the load-bearing decisions:

- `Product` stays store-scoped (unchanged from M0-M7): a transfer line
  references TWO distinct product rows — `source_product_id` (in
  `from_store_id`) and `destination_product_id` (in `to_store_id`, must
  already exist — never auto-created).
- No separate REQUESTED/APPROVED states: DRAFT -> SHIPPED -> RECEIVED
  (RECEIVED is a derived fact, not a stored status — see below).
- Shipping is a single event per transfer (`InterStoreTransfer` itself
  carries the ship-time fields); receiving may happen across several
  events (`InterStoreTransferReceipt`, mirroring `GoodsReceipt` exactly).
"""

from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base_class import Base, TimestampMixin

# RECEIVED is deliberately not a stored status — see the module docstring
# and docs/M8_ADVANCED_INVENTORY_DESIGN.md "Design Decision 7": "fully
# received" is the derived fact that every line's received_quantity has
# reached its shipped_quantity, computed at read time, never stored
# redundantly (the same reasoning PurchaseInvoice.balance_due follows).
TRANSFER_STATUSES = ("DRAFT", "SHIPPED", "CANCELLED")
_CANCELLABLE_TRANSFER_STATUSES = ("DRAFT",)


class InterStoreTransfer(TimestampMixin, Base):
    __tablename__ = "inter_store_transfers"
    __table_args__ = (
        UniqueConstraint("transfer_number", name="uq_inter_store_transfers_number"),
        CheckConstraint(
            "status IN ('" + "', '".join(TRANSFER_STATUSES) + "')",
            name="ck_inter_store_transfers_status",
        ),
        CheckConstraint(
            "from_store_id <> to_store_id", name="ck_inter_store_transfers_distinct_stores"
        ),
        Index("ix_inter_store_transfers_from_store_id", "from_store_id"),
        Index("ix_inter_store_transfers_to_store_id", "to_store_id"),
        Index("ix_inter_store_transfers_status", "status"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    from_store_id: Mapped[int] = mapped_column(ForeignKey("stores.id"), nullable=False)
    to_store_id: Mapped[int] = mapped_column(ForeignKey("stores.id"), nullable=False)
    transfer_number: Mapped[str] = mapped_column(String(64), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="DRAFT")
    requested_date: Mapped[date] = mapped_column(Date, nullable=False)
    notes: Mapped[str | None] = mapped_column(Text)
    requested_by: Mapped[int | None] = mapped_column(ForeignKey("users.id"))
    # Ship-time fields — a transfer ships exactly once (Design Decision 8).
    # `ship_client_transaction_id` is the idempotency key for that one
    # event, unique so a retried request is safely recoverable exactly
    # like every other mutating endpoint in this codebase.
    ship_client_transaction_id: Mapped[str | None] = mapped_column(String(100), unique=True)
    shipped_by: Mapped[int | None] = mapped_column(ForeignKey("users.id"))
    shipped_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    cancelled_by: Mapped[int | None] = mapped_column(ForeignKey("users.id"))
    cancelled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # M9 (docs/M9_SUPPLY_CHAIN_DESIGN.md "Design Decision 9"): set only
    # when this transfer was generated by executing a replenishment plan
    # — NULL for every manually-created transfer (unchanged from M8).
    replenishment_plan_id: Mapped[int | None] = mapped_column(ForeignKey("replenishment_plans.id"))

    lines: Mapped[list["InterStoreTransferLine"]] = relationship(back_populates="transfer")
    receipts: Mapped[list["InterStoreTransferReceipt"]] = relationship(back_populates="transfer")


class InterStoreTransferLine(TimestampMixin, Base):
    __tablename__ = "inter_store_transfer_lines"
    __table_args__ = (
        CheckConstraint(
            "requested_quantity > 0", name="ck_inter_store_transfer_lines_requested_positive"
        ),
        CheckConstraint(
            "shipped_quantity >= 0 AND shipped_quantity <= requested_quantity",
            name="ck_inter_store_transfer_lines_shipped_bounds",
        ),
        # M25 Phase 2 (docs/M24D_TECHNICAL_CONTRACT.md Section 5): the
        # single-table proxy for the quantity-ledger identity -- every
        # unit shipped is eventually good, damaged, declared short, or
        # still outstanding (remaining_in_transit, never stored --
        # derived as shipped_quantity minus the other three, the same
        # "don't store a redundant derived fact" rule RECEIVED already
        # follows). received_quantity's historical name is kept
        # unchanged; it means "good" as of this phase.
        CheckConstraint(
            "received_quantity >= 0 AND damaged_quantity >= 0 AND "
            "declared_short_quantity >= 0 AND "
            "(received_quantity + damaged_quantity + declared_short_quantity) <= "
            "shipped_quantity",
            name="ck_inter_store_transfer_lines_received_bounds",
        ),
        Index("ix_inter_store_transfer_lines_transfer_id", "transfer_id"),
        Index("ix_inter_store_transfer_lines_source_product_id", "source_product_id"),
        Index("ix_inter_store_transfer_lines_destination_product_id", "destination_product_id"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    transfer_id: Mapped[int] = mapped_column(ForeignKey("inter_store_transfers.id"), nullable=False)
    source_product_id: Mapped[int] = mapped_column(ForeignKey("products.id"), nullable=False)
    destination_product_id: Mapped[int] = mapped_column(ForeignKey("products.id"), nullable=False)
    requested_quantity: Mapped[Decimal] = mapped_column(Numeric(14, 3), nullable=False)
    shipped_quantity: Mapped[Decimal] = mapped_column(Numeric(14, 3), nullable=False, default=0)
    # "Good" quantity received to date, across every receipt event for
    # this line (M25 Phase 2: the column name predates the
    # good/damaged/short split and is kept for compatibility -- see
    # docs/M24D_TECHNICAL_CONTRACT.md Section 3.1).
    received_quantity: Mapped[Decimal] = mapped_column(Numeric(14, 3), nullable=False, default=0)
    # New in M25 Phase 2: cumulative damaged/declared-short quantity
    # across every receipt event for this line. Neither creates an
    # inventory movement or a GL posting here -- both remain explicit,
    # unresolved physical-discrepancy facts for a later phase to
    # consume (Section 5/9 -- no write-off, no vendor claim yet).
    damaged_quantity: Mapped[Decimal] = mapped_column(Numeric(14, 3), nullable=False, default=0)
    declared_short_quantity: Mapped[Decimal] = mapped_column(
        Numeric(14, 3), nullable=False, default=0
    )
    # Frozen at ship time from the SOURCE product's current_cost — never
    # recomputed from the destination's WAC (Design Decision 4/9). NULL
    # until shipped.
    unit_cost_at_shipment: Mapped[Decimal | None] = mapped_column(Numeric(14, 6))

    transfer: Mapped[InterStoreTransfer] = relationship(back_populates="lines")


class InterStoreTransferReceipt(TimestampMixin, Base):
    """One physical receiving event against a transfer — a transfer may
    have several, mirroring GoodsReceipt/GoodsReceiptItem exactly (Design
    Decision 8)."""

    __tablename__ = "inter_store_transfer_receipts"
    __table_args__ = (Index("ix_inter_store_transfer_receipts_transfer_id", "transfer_id"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    transfer_id: Mapped[int] = mapped_column(ForeignKey("inter_store_transfers.id"), nullable=False)
    store_id: Mapped[int] = mapped_column(ForeignKey("stores.id"), nullable=False)
    client_transaction_id: Mapped[str] = mapped_column(String(100), nullable=False, unique=True)
    received_date: Mapped[date] = mapped_column(Date, nullable=False)
    received_by: Mapped[int | None] = mapped_column(ForeignKey("users.id"))
    notes: Mapped[str | None] = mapped_column(Text)

    transfer: Mapped[InterStoreTransfer] = relationship(back_populates="receipts")
    items: Mapped[list["InterStoreTransferReceiptItem"]] = relationship(back_populates="receipt")
    custody_acceptance: Mapped["TransferCustodyAcceptance | None"] = relationship(
        back_populates="receipt", uselist=False
    )


class InterStoreTransferReceiptItem(TimestampMixin, Base):
    __tablename__ = "inter_store_transfer_receipt_items"
    __table_args__ = (
        # M25 Phase 2: a single raw input line may now record any mix of
        # good/damaged/declared-short, as long as at least one is
        # positive (an all-zero line is rejected as malformed before it
        # ever reaches here -- see transfers/service.py). Individually
        # non-negative so neither a damage-only nor a shortage-only
        # receiving event is blocked.
        CheckConstraint(
            "quantity_received >= 0 AND quantity_damaged >= 0 AND "
            "quantity_declared_short >= 0 AND "
            "(quantity_received + quantity_damaged + quantity_declared_short) > 0",
            name="ck_inter_store_transfer_receipt_items_qty_positive",
        ),
        Index(
            "ix_inter_store_transfer_receipt_items_receipt_id",
            "inter_store_transfer_receipt_id",
        ),
        Index("ix_inter_store_transfer_receipt_items_line_id", "inter_store_transfer_line_id"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    inter_store_transfer_receipt_id: Mapped[int] = mapped_column(
        ForeignKey("inter_store_transfer_receipts.id"), nullable=False
    )
    inter_store_transfer_line_id: Mapped[int] = mapped_column(
        ForeignKey("inter_store_transfer_lines.id"), nullable=False
    )
    # "Good" quantity for this specific receiving event/line (see
    # InterStoreTransferLine.received_quantity's docstring for the name).
    quantity_received: Mapped[Decimal] = mapped_column(Numeric(14, 3), nullable=False, default=0)
    quantity_damaged: Mapped[Decimal] = mapped_column(Numeric(14, 3), nullable=False, default=0)
    quantity_declared_short: Mapped[Decimal] = mapped_column(
        Numeric(14, 3), nullable=False, default=0
    )

    receipt: Mapped[InterStoreTransferReceipt] = relationship(back_populates="items")


class TransferCustodyAcceptance(TimestampMixin, Base):
    """M25 Phase 2 (docs/M24D_TECHNICAL_CONTRACT.md Section 11): the
    immutable, digital custody-acceptance record for one receiving event.
    Created in the SAME transaction as the InterStoreTransferReceipt it
    belongs to -- the receiving action itself IS the custody acceptance
    (no separate "sign now, count later" step exists in this design; see
    Section 11 for why). This record is the operative boundary a later
    phase uses to distinguish loss attribution before vs. after
    destination custody.

    Not a legally compliant electronic signature -- an internal ERP
    custody acknowledgment only (the authenticated receiving user's
    identity, action, and timestamp), unless a future requirement
    explicitly establishes legal-signature functionality.

    UPDATE/DELETE are revoked from the application runtime role in the
    migration, the same carve-out journal_entries/accounting_periods use,
    since this is evidentiary, append-only history.
    """

    __tablename__ = "inter_store_transfer_custody_acceptances"
    __table_args__ = (
        UniqueConstraint(
            "inter_store_transfer_receipt_id",
            name="uq_inter_store_transfer_custody_acceptances_receipt_id",
        ),
        Index(
            "ix_inter_store_transfer_custody_acceptances_transfer_id",
            "transfer_id",
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    transfer_id: Mapped[int] = mapped_column(ForeignKey("inter_store_transfers.id"), nullable=False)
    inter_store_transfer_receipt_id: Mapped[int] = mapped_column(
        ForeignKey("inter_store_transfer_receipts.id"), nullable=False
    )
    store_id: Mapped[int] = mapped_column(ForeignKey("stores.id"), nullable=False)
    accepted_by: Mapped[int | None] = mapped_column(ForeignKey("users.id"))
    accepted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    is_digital_acknowledgment: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)

    receipt: Mapped[InterStoreTransferReceipt] = relationship(back_populates="custody_acceptance")
