"""Fiscal-submission service layer (docs/M20_DESIGN.md Sections 2-3).

Two entry points, deliberately kept separate:

- `create_fiscal_submission_if_enabled` runs INSIDE `finalize_sale`'s own
  transaction (cheap, local, no network) -- it only ever writes the
  outbox row. It is a no-op whenever the sale's store has no enabled
  `FiscalConfig`, which is every store today (docs/M20_DISCOVERY.md
  Section 1: no jurisdiction is established).
- `submit_fiscal_transaction` is the network-touching step, called
  separately (via `BackgroundTasks` right after checkout, or via the
  manual retry endpoint/an operator-triggered re-run) -- never inside the
  sale's own DB transaction (Phase 2's explicit instruction: "do not
  solve external API reliability by simply putting the entire HTTP
  request inside a database transaction").
"""

from __future__ import annotations

from datetime import UTC, datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.exceptions import NotFoundError
from app.db.session import SessionLocal
from app.modules.audit import service as audit_service
from app.modules.fiscal.models import FiscalConfig, FiscalSubmission, is_terminal_fiscal_status
from app.modules.fiscal.provider import FiscalProvider, FiscalProviderError, NullFiscalProvider
from app.modules.sales.models import Sale

_PROVIDERS: dict[str, FiscalProvider] = {"NULL": NullFiscalProvider()}


def register_provider(name: str, provider: FiscalProvider) -> None:
    """Registers an adapter under `name` so `FiscalConfig.provider_name`
    can select it. Tests use this to register `FakeFiscalProvider` as
    "FAKE" -- see `backend/tests/fiscal_fakes.py`. No real adapter is
    registered anywhere in this codebase (docs/M20_DISCOVERY.md Section
    1: no jurisdiction is established)."""
    _PROVIDERS[name] = provider


def _resolve_provider(provider_name: str) -> FiscalProvider:
    try:
        return _PROVIDERS[provider_name]
    except KeyError as exc:
        raise NotFoundError(f"No fiscal provider registered under {provider_name!r}") from exc


def _build_fiscal_payload(sale: Sale) -> dict[str, Any]:
    """Built once, read-only, entirely from `Sale`'s/`SaleItem`'s own
    already-frozen, already-posted fields -- never a second, independent
    calculation (docs/M20_DESIGN.md Section 4). Every value here is
    guaranteed equal to the sale's own stored totals and the GL postings
    derived from them, by construction, not by cross-checking."""

    def _money(value: Decimal) -> str:
        # Always 2 decimal places, regardless of how many digits the
        # in-memory Decimal happens to carry before its first DB
        # round-trip (e.g. a freshly-summed Decimal("0") vs. the same
        # value re-read from a NUMERIC(12,2) column as Decimal("0.00")) --
        # the payload's own formatting must be canonical on its own,
        # not an accident of when in the sale's lifecycle it was built.
        return str(value.quantize(Decimal("0.01")))

    return {
        "idempotency_key": f"sale-{sale.id}",
        "sale_id": sale.id,
        "store_id": sale.store_id,
        "sale_number": sale.sale_number,
        "completed_at": sale.completed_at.isoformat() if sale.completed_at else None,
        "subtotal": _money(sale.subtotal),
        "discount_total": _money(sale.discount_total),
        "tax_total": _money(sale.tax_total),
        "grand_total": _money(sale.grand_total),
        "lines": [
            {
                "product_id": item.product_id,
                "quantity": str(item.quantity),
                "unit_price": _money(item.unit_price_at_sale),
                "discount_amount": _money(item.discount_amount),
                "tax_rate_id": item.tax_rate_id,
                "tax_amount": _money(item.tax_amount),
                "line_total": _money(item.line_total),
            }
            for item in sale.items
        ],
    }


def create_fiscal_submission_if_enabled(db: Session, sale: Sale) -> FiscalSubmission | None:
    """Called from `app.modules.sales.service.finalize_sale`, in the same
    still-open transaction as the sale itself. Returns None (writing
    nothing) whenever the store has no `FiscalConfig` row, or has one
    with `is_enabled=False` -- the default, and the only value ever
    seeded, for every store.

    No IntegrityError-recovery block is needed here, unlike every other
    idempotency key in this codebase: `FiscalSubmission.sale_id`'s
    uniqueness is enforced against `sale.id`, a primary key that was just
    freshly generated by `Sale`'s own insert a few lines above this call
    in `finalize_sale` -- it is structurally impossible for a fresh
    primary key to already exist as another row's `sale_id`, so no
    concurrent-duplicate race is possible here the way one is for a
    client-supplied key.
    """
    config = db.execute(
        select(FiscalConfig).where(FiscalConfig.store_id == sale.store_id)
    ).scalar_one_or_none()
    if config is None or not config.is_enabled:
        return None

    submission = FiscalSubmission(
        sale_id=sale.id,
        store_id=sale.store_id,
        status="PENDING",
        provider_name=config.provider_name,
        attempt_count=0,
        max_attempts=config.retry_max_attempts,
        request_payload=_build_fiscal_payload(sale),
    )
    db.add(submission)
    db.flush()
    return submission


def submit_fiscal_transaction(db: Session, submission_id: int) -> FiscalSubmission:
    """The one network-touching step. Idempotent and safely re-entrant:
    re-reads the submission's current status first and no-ops for any
    terminal one (ACKNOWLEDGED/REJECTED/EXHAUSTED), so calling this
    again -- sequentially, concurrently, or after a process restart --
    never re-invokes the provider for an already-resolved submission
    (docs/M20_DESIGN.md Section 3).

    Does not call `db.commit()` itself -- callers commit, exactly like
    every other service function in this codebase (route handlers for
    the retry endpoint; `run_pending_fiscal_submission_in_background`
    below for the best-effort post-checkout attempt, which owns its own
    session and commit).

    Locks the submission row `FOR UPDATE` for the duration of the call
    (the same `with_for_update` pattern `inventory.lock_product_for_update`/
    `StockCount` locking already use), exactly like every other lock in
    this codebase -- but unlike those, this one is held across the actual
    network attempt. That is a deliberate, narrow exception to Phase 2's
    "don't wrap a network call in a database transaction" principle: the
    lock is scoped to exactly one already-independent submission row (the
    sale's own transaction already committed before this function is ever
    called), so it cannot block checkout, unrelated submissions, or any
    other sale -- it only serializes two genuinely concurrent attempts to
    submit the SAME submission (e.g. the background task and a manual
    retry racing), which is exactly the race this exists to prevent.
    """
    submission = db.execute(
        select(FiscalSubmission).where(FiscalSubmission.id == submission_id).with_for_update()
    ).scalar_one_or_none()
    if submission is None:
        raise NotFoundError(f"Fiscal submission {submission_id} not found")
    if is_terminal_fiscal_status(submission.status):
        return submission

    config = db.execute(
        select(FiscalConfig).where(FiscalConfig.store_id == submission.store_id)
    ).scalar_one_or_none()
    if config is None or not config.is_enabled:
        # Fiscalization was disabled for this store after the row was
        # created (an operator decision, not a failure) -- leave the
        # submission exactly as it is; it will be picked up again if
        # fiscalization is re-enabled and this function is called again.
        return submission

    provider = _resolve_provider(submission.provider_name)
    submission.attempt_count += 1
    submission.last_attempted_at = datetime.now(UTC)

    try:
        outcome = provider.submit(submission.request_payload)
    except FiscalProviderError as exc:
        submission.last_error = str(exc)
        submission.status = (
            "EXHAUSTED" if submission.attempt_count >= submission.max_attempts else "FAILED"
        )
        db.flush()
        return submission

    submission.response_payload = outcome.raw_response
    submission.fiscal_reference = outcome.fiscal_reference
    submission.submitted_at = datetime.now(UTC)
    submission.status = outcome.status
    db.flush()
    return submission


def get_config(db: Session, store_id: int) -> FiscalConfig | None:
    return db.execute(
        select(FiscalConfig).where(FiscalConfig.store_id == store_id)
    ).scalar_one_or_none()


def upsert_config(
    db: Session,
    *,
    store_id: int,
    is_enabled: bool,
    provider_name: str,
    credential_reference: str | None,
    submission_endpoint: str | None,
    retry_max_attempts: int,
    updated_by: int,
    ip_address: str | None = None,
    user_agent: str | None = None,
) -> FiscalConfig:
    """Create-or-update, one row per store (docs/M20_DESIGN.md Section
    1.1). Audited before/after exactly like every other config-mutation
    path in this codebase -- `credential_reference` is a NAME, not a
    secret value, so recording it in the audit trail is safe (Section 6:
    there is no secret value stored here to leak)."""
    config = get_config(db, store_id)
    before = (
        {
            "is_enabled": config.is_enabled,
            "provider_name": config.provider_name,
            "credential_reference": config.credential_reference,
            "submission_endpoint": config.submission_endpoint,
            "retry_max_attempts": config.retry_max_attempts,
        }
        if config is not None
        else None
    )
    if config is None:
        config = FiscalConfig(store_id=store_id)
        db.add(config)
    config.is_enabled = is_enabled
    config.provider_name = provider_name
    config.credential_reference = credential_reference
    config.submission_endpoint = submission_endpoint
    config.retry_max_attempts = retry_max_attempts
    config.updated_by = updated_by
    db.flush()

    audit_service.log_event(
        db,
        user_id=updated_by,
        action="FISCAL_CONFIG_UPDATED",
        entity_type="fiscal_config",
        entity_id=config.id,
        before=before,
        after={
            "is_enabled": config.is_enabled,
            "provider_name": config.provider_name,
            "credential_reference": config.credential_reference,
            "submission_endpoint": config.submission_endpoint,
            "retry_max_attempts": config.retry_max_attempts,
        },
        ip_address=ip_address,
        user_agent=user_agent,
    )
    return config


def get_submission(db: Session, submission_id: int) -> FiscalSubmission:
    submission = db.get(FiscalSubmission, submission_id)
    if submission is None:
        raise NotFoundError(f"Fiscal submission {submission_id} not found")
    return submission


def list_submissions(
    db: Session,
    *,
    store_id: int | None,
    status: str | None = None,
    limit: int = 50,
    offset: int = 0,
) -> list[FiscalSubmission]:
    query = select(FiscalSubmission).order_by(FiscalSubmission.id.desc())
    if store_id is not None:
        query = query.where(FiscalSubmission.store_id == store_id)
    if status is not None:
        query = query.where(FiscalSubmission.status == status)
    query = query.limit(limit).offset(offset)
    return list(db.execute(query).scalars())


def run_pending_fiscal_submission_in_background(submission_id: int) -> None:
    """The `BackgroundTasks` target scheduled right after a `POST /sales`
    response is sent (docs/M20_DESIGN.md Section 2.1) -- runs after the
    request's own DB session has already closed, so it opens and owns a
    fresh one. Any exception is swallowed after being recorded on the
    submission row: a background attempt failing must never surface as a
    500 to a cashier who has already received their (successful) sale
    response, and the durable row plus the retry endpoint are the real
    recovery path (docs/M20_DESIGN.md Section 2.1 item 2), not this
    best-effort attempt.
    """
    db = SessionLocal()
    try:
        submit_fiscal_transaction(db, submission_id)
        db.commit()
    except Exception:
        db.rollback()
    finally:
        db.close()
