"""M9 hardening pass, Phase 5 (TOCTOU) additions not already covered by
test_replenishment_m9.py (position recovery, source surplus vanishing)
or test_replenishment_concurrency_matrix.py (source inventory races,
destination demand races, supplier price races): an inbound PO appearing
between approval and execution, an inbound transfer being SHIPPED between
approval and execution, and a supplier's MOQ changing between approval
and execution. Each proves execute_plan's deterministic rule: recompute
fresh and either execute the (possibly reduced) quantity, or mark STALE
if nothing remains — never silently use a stale generation-time value."""

from datetime import date
from decimal import Decimal

import pytest
from sqlalchemy.orm import Session

from app.core.exceptions import ConflictError
from app.modules.purchasing import service as purchasing_service
from app.modules.replenishment import service as replenishment_service
from app.modules.transfers import service as transfer_service
from app.modules.transfers.service import ShipLineInput, TransferLineInput
from tests.factories import make_product, make_store, make_supplier, make_supplier_product


def test_inbound_po_appearing_after_approval_reduces_or_staleifies_execution(db: Session) -> None:
    """A DIFFERENT purchase order (not generated by this plan) arrives
    and is submitted between approval and execution, fully covering the
    shortfall. execute_plan must recompute shortfall fresh and either
    execute for a reduced amount or mark the plan STALE — never execute
    for the full originally-approved quantity while double-counting
    supply the other PO already committed."""
    store = make_store(db)
    supplier = make_supplier(db)
    product = make_product(db, store, current_qty_on_hand=Decimal("2"), reorder_point=Decimal("10"))
    db.commit()
    make_supplier_product(db, supplier, product, unit_cost=Decimal("1.00"))
    db.commit()
    (plan,) = replenishment_service.generate_replenishment_plans(db, store_id=store.id)
    db.commit()
    replenishment_service.approve_plan(db, plan.id, actor_id=None, caller_store_id=None)
    db.commit()
    approved_quantity = plan.suggested_quantity

    # An unrelated PO for the same product arrives and is placed
    # (ORDERED, which is already an "open" status), covering the full
    # shortfall on its own.
    other_po = purchasing_service.create_purchase_order(
        db,
        store_id=store.id,
        supplier_id=supplier.id,
        order_date=date.today(),
        lines=[
            purchasing_service.PurchaseOrderItemInput(
                product_id=product.id, quantity_ordered=Decimal("8"), unit_cost=Decimal("1.00")
            )
        ],
    )
    purchasing_service.submit_purchase_order(db, other_po.id, actor_id=None, caller_store_id=None)
    db.commit()

    # Per the deterministic rule, the CURRENT shortfall (now 0, since the
    # other PO already covers it) must cause a STALE outcome, never a
    # successful execution that would double-count supply.
    with pytest.raises(ConflictError) as exc_info:
        replenishment_service.execute_plan(
            db, plan.id, actor_id=None, caller_store_id=None, client_transaction_id="toctou-po"
        )
    assert exc_info.value.error_code == "STALE_RECOMMENDATION"

    reloaded = replenishment_service.get_plan(db, plan.id)
    assert reloaded.status == "STALE"
    assert reloaded.generated_purchase_order_id is None
    assert approved_quantity > 0  # sanity: there really was something approved


def test_inbound_transfer_shipping_after_approval_reduces_or_staleifies_execution(
    db: Session,
) -> None:
    """An UNRELATED transfer (not generated by this plan) ships to the
    same destination product between approval and execution, fully
    covering the shortfall once SHIPPED (which is what actually counts
    toward inbound_transfer_qty — see Design Decision 1)."""
    store_source = make_store(db)
    store_dest = make_store(db)
    supplier = make_supplier(db)
    sku = "SKU-TOCTOU-INBOUND-TRANSFER"
    make_product(db, store_source, sku=sku, current_qty_on_hand=Decimal("100"))
    product = make_product(
        db, store_dest, sku=sku, current_qty_on_hand=Decimal("2"), reorder_point=Decimal("10")
    )
    db.commit()
    make_supplier_product(db, supplier, product, unit_cost=Decimal("1.00"))
    db.commit()
    (plan,) = replenishment_service.generate_replenishment_plans(db, store_id=store_dest.id)
    db.commit()
    replenishment_service.approve_plan(db, plan.id, actor_id=None, caller_store_id=None)
    db.commit()

    source_product = db.query(type(product)).filter_by(store_id=store_source.id, sku=sku).one()
    other_transfer = transfer_service.create_transfer(
        db,
        from_store_id=store_source.id,
        to_store_id=store_dest.id,
        requested_date=date.today(),
        lines=[
            TransferLineInput(source_product_id=source_product.id, requested_quantity=Decimal("8"))
        ],
        caller_store_id=None,
    )
    db.commit()
    transfer_service.ship_transfer(
        db,
        transfer_id=other_transfer.id,
        lines=[
            ShipLineInput(
                transfer_line_id=other_transfer.lines[0].id, quantity_to_ship=Decimal("8")
            )
        ],
        client_transaction_id="toctou-inbound-ship",
        caller_store_id=None,
    )
    db.commit()

    with pytest.raises(ConflictError) as exc_info:
        replenishment_service.execute_plan(
            db,
            plan.id,
            actor_id=None,
            caller_store_id=None,
            client_transaction_id="toctou-transfer",
        )
    assert exc_info.value.error_code == "STALE_RECOMMENDATION"

    reloaded = replenishment_service.get_plan(db, plan.id)
    assert reloaded.status == "STALE"
    assert reloaded.generated_purchase_order_id is None
    assert reloaded.generated_transfer_id is None


def test_supplier_moq_change_between_approval_and_execution_uses_fresh_moq(db: Session) -> None:
    """The plan's suggested_quantity was rounded against the MOQ/pack
    size at GENERATION time; if the supplier's terms change before
    EXECUTION, the actually-created PO line must be rounded against the
    CURRENT (post-change) MOQ/pack, never the stale generation-time
    rounding — this is Design Decision 7 combined with design answer
    #18's 'always re-read fresh' rule."""
    store = make_store(db)
    supplier = make_supplier(db)
    product = make_product(db, store, current_qty_on_hand=Decimal("2"), reorder_point=Decimal("10"))
    db.commit()
    make_supplier_product(
        db, supplier, product, unit_cost=Decimal("1.00"), minimum_order_quantity=None
    )
    db.commit()
    (plan,) = replenishment_service.generate_replenishment_plans(db, store_id=store.id)
    db.commit()
    assert plan.suggested_quantity == Decimal("8")  # no MOQ in effect yet
    replenishment_service.approve_plan(db, plan.id, actor_id=None, caller_store_id=None)
    db.commit()

    # Supplier terms change: a new price/MOQ row with a later
    # effective_date, exactly Design Decision 2's insert-only pattern.
    replenishment_service.create_supplier_product(
        db,
        supplier_id=supplier.id,
        product_id=product.id,
        supplier_sku=None,
        pack_size=Decimal("1"),
        unit_cost=Decimal("1.00"),
        minimum_order_quantity=Decimal("50"),
        lead_time_days=None,
        effective_date=date.today(),
        actor_id=None,
    )
    db.commit()

    executed = replenishment_service.execute_plan(
        db, plan.id, actor_id=None, caller_store_id=None, client_transaction_id="toctou-moq"
    )
    assert executed.status == "EXECUTED"
    # Rounded up to the NEW MOQ of 50, not the stale generation-time
    # suggested_quantity of 8.
    assert executed.executed_quantity == Decimal("50")

    from app.modules.purchasing.models import PurchaseOrderItem

    item = (
        db.query(PurchaseOrderItem)
        .filter_by(purchase_order_id=executed.generated_purchase_order_id)
        .one()
    )
    assert item.quantity_ordered == Decimal("50")
