"""m1 transactional data model: catalog, inventory, purchasing, sales, tax

Revision ID: 5914a2603ce7
Revises: 7b22f673d866
Create Date: 2026-09-11 06:14:42.433658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5914a2603ce7'
down_revision: Union[str, None] = '7b22f673d866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_product_categories_parent_name')
    )
    op.create_index('uq_product_categories_top_level_name', 'product_categories', ['name'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_tax_rates_effective_range'),
    sa.CheckConstraint('rate_percent >= 0 AND rate_percent <= 100', name='ck_tax_rates_rate_bounds'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tax_rates_active_effective', 'tax_rates', ['is_active', 'effective_from'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('default_supplier_id', sa.Integer(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=16), nullable=False),
    sa.Column('is_weighed', sa.Boolean(), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_cost', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('tax_rate_id', sa.Integer(), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('current_qty_on_hand', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('allow_negative_stock', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("unit_of_measure IN ('each', 'kg', 'g', 'l', 'ml')", name='ck_products_unit_of_measure'),
    sa.CheckConstraint('allow_negative_stock OR current_qty_on_hand >= 0', name='ck_products_stock_non_negative_unless_allowed'),
    sa.CheckConstraint('current_cost >= 0', name='ck_products_cost_non_negative'),
    sa.CheckConstraint('current_price >= 0', name='ck_products_price_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['default_supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku', name='uq_products_store_sku')
    )
    op.create_index('ix_products_category_id', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_default_supplier_id', 'products', ['default_supplier_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost_at_movement', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('resulting_quantity_on_hand', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(movement_type IN ('PURCHASE_RECEIPT', 'SALE_RETURN', 'STOCK_ADJUSTMENT_IN') AND quantity_delta > 0) OR (movement_type IN ('SALE', 'PURCHASE_RETURN', 'STOCK_ADJUSTMENT_OUT') AND quantity_delta < 0)", name='ck_inventory_movements_direction'),
    sa.CheckConstraint("movement_type IN ('PURCHASE_RECEIPT', 'SALE_RETURN', 'STOCK_ADJUSTMENT_IN', 'SALE', 'PURCHASE_RETURN', 'STOCK_ADJUSTMENT_OUT')", name='ck_inventory_movements_type'),
    sa.CheckConstraint("reference_type IN ('purchase_order', 'sale', 'sale_return', 'purchase_return', 'stock_adjustment')", name='ck_inventory_movements_reference_type'),
    sa.CheckConstraint('quantity_delta <> 0', name='ck_inventory_movements_delta_nonzero'),
    sa.CheckConstraint('unit_cost_at_movement >= 0', name='ck_inventory_movements_unit_cost_non_negative'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_movements_product_created', 'inventory_movements', ['product_id', 'created_at'], unique=False)
    op.create_index('ix_inventory_movements_reference', 'inventory_movements', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_inventory_movements_store_id', 'inventory_movements', ['store_id'], unique=False)
    op.create_table('product_barcodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('barcode_type', sa.String(length=20), nullable=False),
    sa.Column('pack_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("barcode_type IN ('EAN13', 'UPC_A', 'CODE128', 'WEIGHT_EMBEDDED', 'INTERNAL')", name='ck_product_barcodes_type'),
    sa.CheckConstraint('pack_quantity > 0', name='ck_product_barcodes_pack_quantity_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode')
    )
    op.create_index('ix_product_barcodes_product_id', 'product_barcodes', ['product_id'], unique=False)
    op.create_index('uq_product_barcodes_one_primary_per_product', 'product_barcodes', ['product_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('purchase_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT', 'ORDERED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED')", name='ck_purchase_orders_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_number', name='uq_purchase_orders_number')
    )
    op.create_index('ix_purchase_orders_store_id', 'purchase_orders', ['store_id'], unique=False)
    op.create_index('ix_purchase_orders_supplier_id', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('sale_number', sa.String(length=64), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_tendered', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('change_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('voided_by', sa.Integer(), nullable=True),
    sa.Column('voided_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('OPEN', 'COMPLETED', 'VOIDED', 'REFUNDED', 'PARTIALLY_REFUNDED')", name='ck_sales_status'),
    sa.CheckConstraint('discount_total >= 0', name='ck_sales_discount_non_negative'),
    sa.CheckConstraint('grand_total = subtotal - discount_total + tax_total', name='ck_sales_grand_total_consistent'),
    sa.CheckConstraint('grand_total >= 0', name='ck_sales_grand_total_non_negative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_sales_subtotal_non_negative'),
    sa.CheckConstraint('tax_total >= 0', name='ck_sales_tax_non_negative'),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_number')
    )
    op.create_index('ix_sales_cashier_id', 'sales', ['cashier_id'], unique=False)
    op.create_index('ix_sales_store_created', 'sales', ['store_id', 'created_at'], unique=False)
    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reason_code', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("reason_code IN ('DAMAGE', 'THEFT', 'EXPIRY', 'STOCKTAKE_CORRECTION', 'OTHER')", name='ck_stock_adjustments_reason_code'),
    sa.CheckConstraint('quantity_delta <> 0', name='ck_stock_adjustments_delta_nonzero'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_adjustments_product_id', 'stock_adjustments', ['product_id'], unique=False)
    op.create_index('ix_stock_adjustments_store_id', 'stock_adjustments', ['store_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goods_receipts_purchase_order_id', 'goods_receipts', ['purchase_order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("payment_method IN ('CASH', 'CARD', 'MOBILE_MONEY', 'BANK_TRANSFER', 'OTHER')", name='ck_payments_method'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_sale_id', 'payments', ['sale_id'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity_ordered > 0', name='ck_purchase_order_items_qty_ordered_positive'),
    sa.CheckConstraint('quantity_received >= 0', name='ck_purchase_order_items_qty_received_non_negative'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_purchase_order_items_unit_cost_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_order_items_purchase_order_id', 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_table('purchase_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_returns_purchase_order_id', 'purchase_returns', ['purchase_order_id'], unique=False)
    op.create_index('ix_purchase_returns_store_id', 'purchase_returns', ['store_id'], unique=False)
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price_at_sale', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost_at_sale', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate_id', sa.Integer(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('discount_amount >= 0', name='ck_sale_items_discount_non_negative'),
    sa.CheckConstraint('line_total = round(quantity * unit_price_at_sale - discount_amount + tax_amount, 2)', name='ck_sale_items_line_total_consistent'),
    sa.CheckConstraint('quantity > 0', name='ck_sale_items_quantity_positive'),
    sa.CheckConstraint('tax_amount >= 0', name='ck_sale_items_tax_non_negative'),
    sa.CheckConstraint('unit_cost_at_sale >= 0', name='ck_sale_items_cost_non_negative'),
    sa.CheckConstraint('unit_price_at_sale >= 0', name='ck_sale_items_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['tax_rate_id'], ['tax_rates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_items_product_id', 'sale_items', ['product_id'], unique=False)
    op.create_index('ix_sale_items_sale_id', 'sale_items', ['sale_id'], unique=False)
    op.create_table('sale_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('return_number', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('refund_method', sa.String(length=20), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("refund_method IN ('CASH', 'CARD', 'MOBILE_MONEY', 'BANK_TRANSFER', 'OTHER')", name='ck_sale_returns_refund_method'),
    sa.CheckConstraint('refund_amount >= 0', name='ck_sale_returns_refund_amount_non_negative'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_number')
    )
    op.create_index('ix_sale_returns_sale_id', 'sale_returns', ['sale_id'], unique=False)
    op.create_index('ix_sale_returns_store_id', 'sale_returns', ['store_id'], unique=False)
    op.create_table('goods_receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goods_receipt_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('condition_notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity_received > 0', name='ck_goods_receipt_items_qty_positive'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_goods_receipt_items_unit_cost_non_negative'),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_item_id'], ['purchase_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goods_receipt_items_goods_receipt_id', 'goods_receipt_items', ['goods_receipt_id'], unique=False)
    op.create_index('ix_goods_receipt_items_purchase_order_item_id', 'goods_receipt_items', ['purchase_order_item_id'], unique=False)
    op.create_table('purchase_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_return_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_return_items_qty_positive'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_purchase_return_items_unit_cost_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_return_id'], ['purchase_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_return_items_purchase_return_id', 'purchase_return_items', ['purchase_return_id'], unique=False)
    op.create_table('sale_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_return_id', sa.Integer(), nullable=False),
    sa.Column('sale_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price_refunded', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('restock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity > 0', name='ck_sale_return_items_quantity_positive'),
    sa.CheckConstraint('unit_price_refunded >= 0', name='ck_sale_return_items_price_non_negative'),
    sa.ForeignKeyConstraint(['sale_item_id'], ['sale_items.id'], ),
    sa.ForeignKeyConstraint(['sale_return_id'], ['sale_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sale_return_items_sale_return_id', 'sale_return_items', ['sale_return_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sale_return_items_sale_return_id', table_name='sale_return_items')
    op.drop_table('sale_return_items')
    op.drop_index('ix_purchase_return_items_purchase_return_id', table_name='purchase_return_items')
    op.drop_table('purchase_return_items')
    op.drop_index('ix_goods_receipt_items_purchase_order_item_id', table_name='goods_receipt_items')
    op.drop_index('ix_goods_receipt_items_goods_receipt_id', table_name='goods_receipt_items')
    op.drop_table('goods_receipt_items')
    op.drop_index('ix_sale_returns_store_id', table_name='sale_returns')
    op.drop_index('ix_sale_returns_sale_id', table_name='sale_returns')
    op.drop_table('sale_returns')
    op.drop_index('ix_sale_items_sale_id', table_name='sale_items')
    op.drop_index('ix_sale_items_product_id', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index('ix_purchase_returns_store_id', table_name='purchase_returns')
    op.drop_index('ix_purchase_returns_purchase_order_id', table_name='purchase_returns')
    op.drop_table('purchase_returns')
    op.drop_index('ix_purchase_order_items_purchase_order_id', table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index('ix_payments_sale_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_goods_receipts_purchase_order_id', table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index('ix_stock_adjustments_store_id', table_name='stock_adjustments')
    op.drop_index('ix_stock_adjustments_product_id', table_name='stock_adjustments')
    op.drop_table('stock_adjustments')
    op.drop_index('ix_sales_store_created', table_name='sales')
    op.drop_index('ix_sales_cashier_id', table_name='sales')
    op.drop_table('sales')
    op.drop_index('ix_purchase_orders_supplier_id', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_store_id', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index('uq_product_barcodes_one_primary_per_product', table_name='product_barcodes', postgresql_where=sa.text('is_primary'))
    op.drop_index('ix_product_barcodes_product_id', table_name='product_barcodes')
    op.drop_table('product_barcodes')
    op.drop_index('ix_inventory_movements_store_id', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_reference', table_name='inventory_movements')
    op.drop_index('ix_inventory_movements_product_created', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('ix_products_default_supplier_id', table_name='products')
    op.drop_index('ix_products_category_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_tax_rates_active_effective', table_name='tax_rates')
    op.drop_table('tax_rates')
    op.drop_table('suppliers')
    op.drop_index('uq_product_categories_top_level_name', table_name='product_categories', postgresql_where=sa.text('parent_id IS NULL'))
    op.drop_table('product_categories')
    # ### end Alembic commands ###
